AllCops:
  TargetRubyVersion: 2.4.0
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Layout/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
