version: 2.1

environment: &environment
  LOG_LEVEL: WARN

jobs:
  run_cops:
    working_directory: ~/repos/fonepaisa

    docker:
      - image: circleci/ruby:2.6.4-buster-node
        environment:
          <<: *environment

    steps:
      - checkout

      - run:
          name: check dependencies
          command: |
            bundle -v
            bundle exec ruby -v

      - run:
          name: install gems
          command: bundle install && bundle clean

      - run:
          name: run rubocop
          command: bundle exec rubocop

workflows:
  version: 2
  build_and_test:
    jobs:
      - run_cops
